person:
  name: John
  hobby:
    - skiing
    - hiking
    - fishing
    - running
    - swimming
  family: Smith
  age: 42
  id: 1
  pet:
    type: dog
    name: fluffy
#  map:
#    key1: value1
#    key2: value2

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    data-username: root
    data-password: 297592781
    driver-class-name: com.mysql.cj.jdbc.Driver