spring:
  datasource:
    initialSize: 20
    maxActive: 100
    minIdle: 10
    password: "297592781"
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.218.90:3306/blog_system?serverTimezone=UTC&useSSL=false
    username: root
