spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC"
    username: root
    password: "297592781"
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 20
      min-idle: 10
      max-active: 100
    driver-class-name: com.mysql.cj.jdbc.Driver